version: "3.7"
services:
  terraform_libs:
    image: ranjithka/terraform:latest
    build: .
    command:
      - /bin/sh
      - -c
      - |
        /bin/terraform init -plugin-dir=/plugins
        /bin/terraform plan
    env_file:
      - aws.env
    volumes:
      - ./aws_terraform/:/terraform
